-- =============================================================================
-- Alpha Access Keys Import Script
-- =============================================================================
--
-- Description: Imports alpha access keys generated by generate-alpha-access-keys.sh
-- into the PostgreSQL database for the Armored Archer v2.1.0 Alpha Testing Program.
--
-- Usage:
--   psql -U postgres -d nakama -f import-alpha-keys.sql
--
-- Or from within psql:
--   \i import-alpha-keys.sql
--
-- Prerequisites:
--   1. Run generate-alpha-access-keys.sh to create keys file
--   2. Ensure alpha_users table exists (see schema below)
--   3. Update :keys_file parameter if needed
--
-- Author: Armored Archer Development Team
-- Version: 1.0
-- Created: 2026-03-16
-- =============================================================================

-- =============================================================================
-- Configuration
-- =============================================================================

-- Set the path to your generated keys file
\set keys_file '/home/alex/armored-archer/backend/scripts/alpha_keys.txt'

-- Alpha program configuration
\set alpha_program_version 'v2.1.0'
\set alpha_start_date '2026-04-01'
\set alpha_end_date '2026-04-21'

-- =============================================================================
-- Schema Setup (Run once)
-- =============================================================================

-- Create alpha_users table if it doesn't exist
CREATE TABLE IF NOT EXISTS alpha_users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    access_key VARCHAR(50) UNIQUE NOT NULL,
    user_id UUID REFERENCES users(id), -- Nakama users table
    access_level VARCHAR(20) NOT NULL DEFAULT 'alpha',
    tier VARCHAR(20) NOT NULL DEFAULT 'active', -- 'core', 'active', 'technical'
    status VARCHAR(20) NOT NULL DEFAULT 'available', -- 'available', 'assigned', 'redeemed', 'revoked', 'expired'
    discord_id VARCHAR(50),
    discord_username VARCHAR(100),
    email VARCHAR(255),
    granted_at TIMESTAMP WITH TIME ZONE,
    redeemed_at TIMESTAMP WITH TIME ZONE,
    expires_at TIMESTAMP WITH TIME ZONE DEFAULT :'alpha_end_date',
    last_activity_at TIMESTAMP WITH TIME ZONE,
    sessions_count INTEGER DEFAULT 0,
    feedback_submitted_count INTEGER DEFAULT 0,
    bugs_reported_count INTEGER DEFAULT 0,
    satisfaction_score INTEGER CHECK (satisfaction_score >= 1 AND satisfaction_score <= 5),
    agreement_signed BOOLEAN DEFAULT FALSE,
    agreement_signed_at TIMESTAMP WITH TIME ZONE,
    notes TEXT,
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_alpha_users_access_key ON alpha_users(access_key);
CREATE INDEX IF NOT EXISTS idx_alpha_users_user_id ON alpha_users(user_id);
CREATE INDEX IF NOT EXISTS idx_alpha_users_status ON alpha_users(status);
CREATE INDEX IF NOT EXISTS idx_alpha_users_tier ON alpha_users(tier);
CREATE INDEX IF NOT EXISTS idx_alpha_users_discord ON alpha_users(discord_id);
CREATE INDEX IF NOT EXISTS idx_alpha_users_email ON alpha_users(email);
CREATE INDEX IF NOT EXISTS idx_alpha_users_expires_at ON alpha_users(expires_at);

-- Create audit log table for tracking alpha user actions
CREATE TABLE IF NOT EXISTS alpha_user_audit_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    alpha_user_id UUID NOT NULL REFERENCES alpha_users(id) ON DELETE CASCADE,
    action VARCHAR(50) NOT NULL, -- 'created', 'assigned', 'redeemed', 'activity', 'feedback', 'bug_report', 'revoked', 'expired'
    old_status VARCHAR(20),
    new_status VARCHAR(20),
    metadata JSONB DEFAULT '{}',
    ip_address INET,
    user_agent TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_alpha_audit_user_id ON alpha_user_audit_log(alpha_user_id);
CREATE INDEX IF NOT EXISTS idx_alpha_audit_action ON alpha_user_audit_log(action);
CREATE INDEX IF NOT EXISTS idx_alpha_audit_created_at ON alpha_user_audit_log(created_at);

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for auto-updating updated_at
DROP TRIGGER IF EXISTS update_alpha_users_updated_at ON alpha_users;
CREATE TRIGGER update_alpha_users_updated_at
    BEFORE UPDATE ON alpha_users
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- =============================================================================
-- Import Keys from File
-- =============================================================================

-- Create temporary table for importing
CREATE TEMP TABLE IF NOT EXISTS temp_alpha_keys (
    access_key VARCHAR(50)
);

-- Clear temporary table
TRUNCATE TABLE temp_alpha_keys;

-- Import keys from file (one key per line)
-- Note: This requires the file to be accessible to the PostgreSQL server
\copy temp_alpha_keys(access_key) FROM :'keys_file'

-- Insert keys into alpha_users table
INSERT INTO alpha_users (access_key, status, tier, expires_at, metadata)
SELECT 
    access_key,
    'available' as status,
    'active' as tier,
    :'alpha_end_date'::timestamp with time zone as expires_at,
    json_build_object(
        'program_version', :'alpha_program_version',
        'imported_at', NOW(),
        'source', 'generate-alpha-access-keys.sh'
    ) as metadata
FROM temp_alpha_keys
ON CONFLICT (access_key) DO NOTHING;

-- Log the import
INSERT INTO alpha_user_audit_log (alpha_user_id, action, metadata)
SELECT 
    id,
    'imported',
    json_build_object(
        'import_source', 'generate-alpha-access-keys.sh',
        'import_file', :'keys_file'
    )
FROM alpha_users
WHERE metadata->>'imported_at' = (SELECT metadata->>'imported_at' FROM alpha_users ORDER BY created_at DESC LIMIT 1);

-- Drop temporary table
DROP TABLE temp_alpha_keys;

-- =============================================================================
-- Verification Queries
-- =============================================================================

-- Show import summary
SELECT 
    'Import Summary' as report,
    COUNT(*) as total_keys,
    COUNT(*) FILTER (WHERE status = 'available') as available,
    COUNT(*) FILTER (WHERE status = 'assigned') as assigned,
    COUNT(*) FILTER (WHERE status = 'redeemed') as redeemed,
    COUNT(*) FILTER (WHERE status = 'revoked') as revoked,
    COUNT(*) FILTER (WHERE status = 'expired') as expired
FROM alpha_users
WHERE metadata->>'source' = 'generate-alpha-access-keys.sh'
  AND metadata->>'imported_at' = (SELECT metadata->>'imported_at' FROM alpha_users ORDER BY created_at DESC LIMIT 1);

-- Show sample of imported keys (first 10)
SELECT 
    access_key,
    status,
    tier,
    created_at
FROM alpha_users
WHERE metadata->>'source' = 'generate-alpha-access-keys.sh'
  AND metadata->>'imported_at' = (SELECT metadata->>'imported_at' FROM alpha_users ORDER BY created_at DESC LIMIT 1)
ORDER BY created_at
LIMIT 10;

-- =============================================================================
-- Utility Functions
-- =============================================================================

-- Function to redeem an alpha key
CREATE OR REPLACE FUNCTION redeem_alpha_key(
    p_access_key VARCHAR(50),
    p_user_id UUID,
    p_email VARCHAR(255),
    p_discord_id VARCHAR(50) DEFAULT NULL
)
RETURNS TABLE(success BOOLEAN, message TEXT, alpha_user_id UUID) AS $$
DECLARE
    v_alpha_user alpha_users%ROWTYPE;
BEGIN
    -- Find the key
    SELECT * INTO v_alpha_user
    FROM alpha_users
    WHERE access_key = p_access_key;
    
    -- Check if key exists
    IF NOT FOUND THEN
        RETURN QUERY SELECT FALSE, 'Invalid access key'::TEXT, NULL::UUID;
        RETURN;
    END IF;
    
    -- Check if already redeemed
    IF v_alpha_user.status = 'redeemed' THEN
        RETURN QUERY SELECT FALSE, 'Access key already redeemed'::TEXT, NULL::UUID;
        RETURN;
    END IF;
    
    -- Check if expired
    IF v_alpha_user.expires_at < NOW() THEN
        RETURN QUERY SELECT FALSE, 'Access key has expired'::TEXT, NULL::UUID;
        RETURN;
    END IF;
    
    -- Check if revoked
    IF v_alpha_user.status = 'revoked' THEN
        RETURN QUERY SELECT FALSE, 'Access key has been revoked'::TEXT, NULL::UUID;
        RETURN;
    END IF;
    
    -- Update the key
    UPDATE alpha_users
    SET 
        status = 'redeemed',
        user_id = p_user_id,
        email = p_email,
        discord_id = p_discord_id,
        redeemed_at = NOW(),
        metadata = metadata || jsonb_build_object('redeemed_ip', inet_client_addr())
    WHERE id = v_alpha_user.id
    RETURNING * INTO v_alpha_user;
    
    -- Log the redemption
    INSERT INTO alpha_user_audit_log (alpha_user_id, action, old_status, new_status, metadata)
    VALUES (v_alpha_user.id, 'redeemed', 'available', 'redeemed', 
            jsonb_build_object('user_id', p_user_id, 'email', p_email));
    
    RETURN QUERY SELECT TRUE, 'Access key redeemed successfully'::TEXT, v_alpha_user.id;
END;
$$ LANGUAGE plpgsql;

-- Function to check if a user has alpha access
CREATE OR REPLACE FUNCTION check_alpha_access(p_user_id UUID)
RETURNS TABLE(has_access BOOLEAN, tier VARCHAR(20), expires_at TIMESTAMP WITH TIME ZONE) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        CASE 
            WHEN au.status = 'redeemed' AND au.expires_at > NOW() THEN TRUE
            ELSE FALSE
        END as has_access,
        au.tier,
        au.expires_at
    FROM alpha_users au
    WHERE au.user_id = p_user_id;
    
    -- If no record found, return false
    IF NOT FOUND THEN
        RETURN QUERY SELECT FALSE, NULL::VARCHAR(20), NULL::TIMESTAMP WITH TIME ZONE;
    END IF;
END;
$$ LANGUAGE plpgsql;

-- Function to grant alpha access manually
CREATE OR REPLACE FUNCTION grant_alpha_access(
    p_user_id UUID,
    p_email VARCHAR(255),
    p_tier VARCHAR(20) DEFAULT 'active',
    p_duration_days INTEGER DEFAULT 30
)
RETURNS UUID AS $$
DECLARE
    v_alpha_user_id UUID;
BEGIN
    INSERT INTO alpha_users (
        access_key,
        user_id,
        email,
        tier,
        status,
        granted_at,
        expires_at,
        metadata
    ) VALUES (
        'MANUAL-' || substr(md5(random()::text), 1, 12),
        p_user_id,
        p_email,
        p_tier,
        'redeemed',
        NOW(),
        NOW() + (p_duration_days || ' days')::interval,
        jsonb_build_object('grant_method', 'manual', 'granted_by', 'admin')
    )
    RETURNING id INTO v_alpha_user_id;
    
    -- Log the grant
    INSERT INTO alpha_user_audit_log (alpha_user_id, action, new_status, metadata)
    VALUES (v_alpha_user_id, 'granted', 'redeemed', 
            jsonb_build_object('user_id', p_user_id, 'tier', p_tier));
    
    RETURN v_alpha_user_id;
END;
$$ LANGUAGE plpgsql;

-- =============================================================================
-- Example Usage Queries
-- =============================================================================

-- Example: Redeem a key (uncomment and modify to use)
-- SELECT * FROM redeem_alpha_key(
--     'ALPHA-XXXX-XXXX-XXXX-XXXX',  -- access key
--     'user-uuid-here',              -- user ID
--     'user@example.com',            -- email
--     'discord-id-here'              -- discord ID (optional)
-- );

-- Example: Check if user has alpha access
-- SELECT * FROM check_alpha_access('user-uuid-here');

-- Example: Grant manual alpha access
-- SELECT grant_alpha_access(
--     'user-uuid-here',
--     'user@example.com',
--     'core',      -- tier
--     60           -- duration in days
-- );

-- =============================================================================
-- Reporting Queries
-- =============================================================================

-- Alpha user statistics
CREATE OR REPLACE VIEW alpha_user_stats AS
SELECT 
    status,
    tier,
    COUNT(*) as count,
    COUNT(*) FILTER (WHERE redeemed_at IS NOT NULL) as redeemed_count,
    COUNT(*) FILTER (WHERE last_activity_at IS NOT NULL) as active_count,
    COUNT(*) FILTER (WHERE feedback_submitted_count > 0) as feedback_count,
    COUNT(*) FILTER (WHERE bugs_reported_count > 0) as bug_reporters,
    AVG(satisfaction_score) as avg_satisfaction,
    AVG(sessions_count) as avg_sessions
FROM alpha_users
GROUP BY status, tier;

-- Daily redemption tracking
CREATE OR REPLACE VIEW alpha_daily_redemptions AS
SELECT 
    DATE(redeemed_at) as redemption_date,
    COUNT(*) as redemptions,
    COUNT(DISTINCT tier) as tiers_represented
FROM alpha_users
WHERE redeemed_at IS NOT NULL
GROUP BY DATE(redeemed_at)
ORDER BY redemption_date;

-- Expiration tracking
CREATE OR REPLACE VIEW alpha_expiring_soon AS
SELECT 
    id,
    access_key,
    user_id,
    email,
    discord_id,
    tier,
    expires_at,
    (expires_at - NOW()) as time_remaining
FROM alpha_users
WHERE status = 'redeemed'
  AND expires_at > NOW()
  AND expires_at < (NOW() + '7 days'::interval)
ORDER BY expires_at;

-- =============================================================================
-- Cleanup and Maintenance
-- =============================================================================

-- Function to expire old keys
CREATE OR REPLACE FUNCTION expire_old_alpha_keys()
RETURNS INTEGER AS $$
DECLARE
    v_count INTEGER;
BEGIN
    UPDATE alpha_users
    SET status = 'expired'
    WHERE status IN ('available', 'assigned')
      AND expires_at < NOW();
    
    GET DIAGNOSTICS v_count = ROW_COUNT;
    
    RETURN v_count;
END;
$$ LANGUAGE plpgsql;

-- Function to revoke alpha access
CREATE OR REPLACE FUNCTION revoke_alpha_access(p_user_id UUID, p_reason TEXT DEFAULT NULL)
RETURNS BOOLEAN AS $$
BEGIN
    UPDATE alpha_users
    SET 
        status = 'revoked',
        metadata = metadata || jsonb_build_object('revoked_at', NOW(), 'revoked_reason', p_reason)
    WHERE user_id = p_user_id;
    
    -- Log the revocation
    INSERT INTO alpha_user_audit_log (alpha_user_id, action, old_status, new_status, metadata)
    SELECT 
        id,
        'revoked',
        status,
        'revoked',
        jsonb_build_object('reason', p_reason)
    FROM alpha_users
    WHERE user_id = p_user_id;
    
    RETURN FOUND;
END;
$$ LANGUAGE plpgsql;

-- =============================================================================
-- End of Script
-- =============================================================================

-- Print completion message
DO $$
BEGIN
    RAISE NOTICE '=============================================';
    RAISE NOTICE 'Alpha Access Keys Import Complete!';
    RAISE NOTICE '=============================================';
    RAISE NOTICE 'Table: alpha_users';
    RAISE NOTICE 'Program: %', :'alpha_program_version';
    RAISE NOTICE 'Start Date: %', :'alpha_start_date';
    RAISE NOTICE 'End Date: %', :'alpha_end_date';
    RAISE NOTICE '=============================================';
END $$;
