/**
 * Property-based tests for the currency-ledger conservation invariant
 * (issue #1099).
 *
 * Documented invariant: the authoritative `player_currency` ledger
 * (`backend/src/modules/currency.ts`) is supposed to be conservation-safe
 * for any sequence of delta applications — i.e. for a player whose
 * balance never hits a floor or a cap, the post-sequence balance equals
 * the pre-sequence balance plus the algebraic sum of every delta in the
 * sequence. This is the invariant the economy dashboards (issue #1092)
 * rely on: if a delta "leaks", the earn/spend counters diverge from the
 * actual ledger state.
 *
 * The production code intentionally has two non-conserving regimes:
 *
 *  - Debits on `coins` are floored at zero (the under-floor delta is
 *    discarded, not carried as negative debt).
 *  - Credits on `gems` are capped at `MAX_GEM_BALANCE` (overflow is
 *    discarded, not carried as over-balance).
 *
 * So the property tested here is the *unfloored, uncapped* regime:
 * given a sequence of deltas drawn from a distribution that provably
 * never pushes the running balance below zero or above `MAX_GEM_BALANCE`,
 * the final balance equals the initial balance plus the exact integer
 * sum of every delta. This catches off-by-one / sign-flip / unit-conversion
 * regressions in `applyCurrencyDelta` without false-positive violations
 * from the legitimate floor / cap.
 *
 * The suite is intentionally dependency-free (no fast-check): a small
 * seeded PRNG keeps runs reproducible. Override the seed with
 * `PROPERTY_TEST_SEED` (same convention as `tests/unit/property_based.test.ts`).
 */
import {
  applyCurrencyDelta,
  getCurrency,
  PLAYER_CURRENCY_COLLECTION,
  MAX_GEM_BALANCE,
  PlayerCurrency,
  CurrencyDelta,
} from '../currency';
import {
  createMockLogger,
  createMockContext,
  createMockNakama,
  testStorage,
} from '../../__mocks__/nakama';
import { Runtime } from '../../types/nakama';

// --- PRNG (mulberry32) -- same scheme as the existing property suite ---

const ITERATIONS = 200;
const SEQUENCE_LENGTH = 25;
const DEFAULT_SEED = 1099;

function makeRng(seed: number): () => number {
  let state = seed >>> 0;
  return (): number => {
    state = (state + 0x6d2b79f5) >>> 0;
    let t = state;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const seed = Number(process.env.PROPERTY_TEST_SEED) || DEFAULT_SEED;
const rng = makeRng(seed);
const randomInt = (min: number, max: number): number =>
  Math.floor(rng() * (max - min + 1)) + min;

/**
 * Builds a credit-only delta sequence that is mathematically guaranteed to
 * never push the balance above `MAX_GEM_BALANCE` (gems) or above an arbitrary
 * coin ceiling. Each entry is in `[+1, +50]` so any length-`SEQUENCE_LENGTH`
 * sequence accumulates at most `50 * 25 = 1250` gems / coins — well inside
 * the cap (10M) and the coin ceiling (1M).
 */
function buildCreditOnlySequence(): CurrencyDelta[] {
  const out: CurrencyDelta[] = [];
  for (let i = 0; i < SEQUENCE_LENGTH; i++) {
    out.push({
      gems: randomInt(1, 50),
      coins: randomInt(1, 50),
    });
  }
  return out;
}

/**
 * Builds a mixed sequence whose debits are bounded by the available balance
 * generated by its own credits. We construct it as pairs: a credit followed
 * by a debit no larger than the credit, so a running balance starting from
 * zero never dips below zero. The total coin / gem movement is therefore
 * sum(credits) − sum(debits), a balanced figure that must reconcile
 * exactly with the final ledger state.
 */
function buildBalancedSequence(): CurrencyDelta[] {
  const out: CurrencyDelta[] = [];
  for (let i = 0; i < SEQUENCE_LENGTH; i++) {
    const gems = randomInt(10, 80);
    const coins = randomInt(10, 80);
    // Slightly smaller debit so the running balance never goes negative.
    const debitGems = randomInt(1, Math.max(1, gems - 5));
    const debitCoins = randomInt(1, Math.max(1, coins - 5));
    out.push({ gems, coins });
    out.push({ gems: -debitGems, coins: -debitCoins });
  }
  return out;
}

/** Sums a delta sequence's algebraic integer total per currency. */
function sumDeltas(deltas: CurrencyDelta[]): { gems: number; coins: number } {
  let gems = 0;
  let coins = 0;
  for (const d of deltas) {
    gems += d.gems ?? 0;
    coins += d.coins ?? 0;
  }
  return { gems, coins };
}

describe('Property-Based Currency Conservation (issue #1099)', () => {
  let mockLogger: Runtime.Logger;
  let mockCtx: Runtime.Context;
  let mockNk: Runtime.Nakama;

  const readLedger = (userId: string): PlayerCurrency | undefined => {
    const raw = testStorage.get(`${PLAYER_CURRENCY_COLLECTION}:${userId}`);
    return raw ? (JSON.parse(raw) as PlayerCurrency) : undefined;
  };

  const writeLedger = (currency: PlayerCurrency): void => {
    testStorage.set(
      `${PLAYER_CURRENCY_COLLECTION}:${currency.user_id}`,
      JSON.stringify(currency)
    );
  };

  beforeEach(() => {
    testStorage.clear();
    mockLogger = createMockLogger();
    mockCtx = createMockContext({ userId: 'prop-currency-user' });
    mockNk = createMockNakama();
  });

  it(
    'credit-only sequence: final balance == sum of deltas (conservation in the uncapped regime)',
    () => {
      for (let iter = 0; iter < ITERATIONS; iter++) {
        const userId = `credit-user-${iter}`;
        const initial = { user_id: userId, gems: 0, coins: 0 };
        writeLedger(initial);

        const deltas = buildCreditOnlySequence();
        for (const delta of deltas) {
          applyCurrencyDelta(mockNk, userId, delta, 'property_test', mockLogger);
        }

        const final = getCurrency(mockNk, userId, mockLogger);
        const expected = sumDeltas(deltas);

        // The conservation invariant: in the regime where neither the
        // coin-floor at zero nor the gem-cap at MAX_GEM_BALANCE is hit,
        // every credit must land in the ledger and be observable on read.
        expect(final.gems).toBe(initial.gems + expected.gems);
        expect(final.coins).toBe(initial.coins + expected.coins);

        // Sanity-check that the ledger storage matches the read-back so
        // the conservation is observable (not just held in cache).
        const stored = readLedger(userId);
        expect(stored).toBeDefined();
        expect(stored!.gems).toBe(initial.gems + expected.gems);
        expect(stored!.coins).toBe(initial.coins + expected.coins);
      }
    }
  );

  it(
    'balanced sequence (paired credit + bounded debit): net balance equals algebraic sum of deltas',
    () => {
      for (let iter = 0; iter < ITERATIONS; iter++) {
        const userId = `balanced-user-${iter}`;
        const initial = { user_id: userId, gems: 0, coins: 0 };
        writeLedger(initial);

        const deltas = buildBalancedSequence();
        for (const delta of deltas) {
          applyCurrencyDelta(mockNk, userId, delta, 'property_test', mockLogger);
        }

        const final = getCurrency(mockNk, userId, mockLogger);
        const expected = sumDeltas(deltas);

        // Running balance is never negative (every debit is bounded by its
        // preceding credit), so the floor-at-zero floor never engages and
        // conservation must hold exactly.
        expect(final.gems).toBe(initial.gems + expected.gems);
        expect(final.coins).toBe(initial.coins + expected.coins);
      }
    }
  );

  it(
    'sequence length is commutative — applying the same deltas in any order yields the same final balance',
    () => {
      // A clean conservation statement: f is commutative under
      // composition when no floor/cap engages.
      for (let iter = 0; iter < ITERATIONS; iter++) {
        const deltas = buildCreditOnlySequence();
        const sum = sumDeltas(deltas);

        const userIdA = `comm-a-${iter}`;
        const userIdB = `comm-b-${iter}`;
        writeLedger({ user_id: userIdA, gems: 0, coins: 0 });
        writeLedger({ user_id: userIdB, gems: 0, coins: 0 });

        for (const d of deltas) {
          applyCurrencyDelta(mockNk, userIdA, d, 'property_test', mockLogger);
        }
        for (const d of [...deltas].reverse()) {
          applyCurrencyDelta(mockNk, userIdB, d, 'property_test', mockLogger);
        }

        const finalA = getCurrency(mockNk, userIdA, mockLogger);
        const finalB = getCurrency(mockNk, userIdB, mockLogger);

        expect(finalA.gems).toBe(sum.gems);
        expect(finalA.coins).toBe(sum.coins);
        expect(finalB.gems).toBe(sum.gems);
        expect(finalB.coins).toBe(sum.coins);
      }
    }
  );

  it(
    'isolated gem vs coin accounting — a coin delta never leaks into the gem balance and vice versa',
    () => {
      // Stronger conservation — the two ledgers must not cross-contaminate.
      for (let iter = 0; iter < ITERATIONS; iter++) {
        const userId = `iso-${iter}`;
        writeLedger({ user_id: userId, gems: 0, coins: 0 });

        const gemDeltas: number[] = [];
        const coinDeltas: number[] = [];
        for (let i = 0; i < SEQUENCE_LENGTH; i++) {
          gemDeltas.push(randomInt(1, 30));
          coinDeltas.push(randomInt(1, 30));
        }

        let expectedGems = 0;
        let expectedCoins = 0;
        for (let i = 0; i < SEQUENCE_LENGTH; i++) {
          applyCurrencyDelta(
            mockNk,
            userId,
            { gems: gemDeltas[i] },
            'property_test',
            mockLogger
          );
          applyCurrencyDelta(
            mockNk,
            userId,
            { coins: coinDeltas[i] },
            'property_test',
            mockLogger
          );
          expectedGems += gemDeltas[i];
          expectedCoins += coinDeltas[i];
        }

        const final = getCurrency(mockNk, userId, mockLogger);
        expect(final.gems).toBe(expectedGems);
        expect(final.coins).toBe(expectedCoins);
      }
    }
  );

  it(
    'gem balance is capped at MAX_GEM_BALANCE — over-cap credit is dropped, not silently retained',
    () => {
      // The documented non-conserving regime: a credit that would push
      // gems above MAX_GEM_BALANCE must cap exactly at the ceiling. This
      // protects the test from passing only because conservation happened
      // to hold; the cap-and-discard behaviour is asserted separately.
      const userId = 'cap-user';
      // Start within [MAX-99, MAX-1] so a single +100 credit definitely
      // overshoots and engages the cap.
      const startGems = MAX_GEM_BALANCE - randomInt(1, 99);
      writeLedger({ user_id: userId, gems: startGems, coins: 0 });

      const credit: CurrencyDelta = { gems: 100, coins: 0 };
      applyCurrencyDelta(mockNk, userId, credit, 'property_test', mockLogger);

      const stored = getCurrency(mockNk, userId, mockLogger);
      expect(stored.gems).toBe(MAX_GEM_BALANCE);
    }
  );
});