#!/usr/bin/env python3
"""
Parse Godot coverage data from coverage.json and generate HTML reports.

This script parses the coverage.json file generated by the GUT coverage plugin
and produces HTML coverage reports similar to 'go tool cover -html'.
"""

import argparse
import json
import sys
from pathlib import Path

# Check for Jinja2 requirement
try:
    from jinja2 import Template
except ImportError:
    print("Error: Jinja2 is required for HTML report generation.")
    print("Install it with: pip install jinja2")
    sys.exit(1)

# JSON parsing implemented in: 13-01-PLAN.md Task 1

def parse_coverage_json(json_path):
    """Parse coverage.json from GUT coverage plugin."""
    try:
        with open(json_path) as f:
            return json.load(f)
    except FileNotFoundError:
        print(f"Error: Coverage file not found: {json_path}")
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON in coverage file: {e}")
        sys.exit(1)


def calculate_overall_coverage(coverage_data):
    """Calculate overall coverage percentage across all files."""
    total_lines = 0
    covered_lines = 0

    # Handle both formats: dict with coverage data, or nested dict with coverage key
    if isinstance(coverage_data, dict) and 'coverage' in coverage_data:
        coverage_data = coverage_data['coverage']

    for _file_path, data in coverage_data.items():
        if isinstance(data, dict):
            total_lines += data.get('total_count', 0)
            covered_lines += data.get('covered_count', 0)

    if total_lines == 0:
        return 0.0

    return round((covered_lines / total_lines) * 100.0, 2)

def get_per_file_coverage(coverage_data):
    """Extract per-file coverage percentages."""
    file_coverage = {}

    # Handle both formats: dict with coverage data, or nested dict with coverage key
    if isinstance(coverage_data, dict) and 'coverage' in coverage_data:
        coverage_data = coverage_data['coverage']

    for file_path, data in coverage_data.items():
        if isinstance(data, dict):
            file_coverage[file_path] = {
                'percentage': data.get('percentage', 0.0),
                'covered_count': data.get('covered_count', 0),
                'total_count': data.get('total_count', 0)
            }

    return file_coverage


def generate_html_report(coverage_data, output_path):
    """Generate HTML coverage report with Jinja2 template."""
    # Handle both formats: dict with coverage data, or nested dict with coverage key
    if isinstance(coverage_data, dict) and 'coverage' in coverage_data:
        coverage_data = coverage_data['coverage']

    # Filter out non-dict entries (like _comment)
    coverage_data = {k: v for k, v in coverage_data.items() if isinstance(v, dict)}

    template = Template('''
<!DOCTYPE html>
<html>
<head>
    <title>Godot Coverage Report</title>
    <style>
        body { font-family: Arial, sans-serif; background: #0F0F1A; color: #F8FAFC; margin: 20px; }
        .covered { background-color: #22C55E; color: #000; }
        .uncovered { background-color: #EF4444; color: #FFF; }
        .line { padding: 2px 5px; font-family: monospace; font-size: 12px; }
        .file-section { margin-bottom: 30px; }
        .file-header { font-weight: bold; margin-bottom: 10px; font-size: 18px; }
        .percentage { font-size: 14px; color: #94A3B8; }
        .badge { padding: 4px 8px; border-radius: 4px; font-size: 12px; font-weight: bold; }
        .badge-success { background: #22C55E; color: white; }
        .badge-warning { background: #F59E0B; color: white; }
        .badge-error { background: #EF4444; color: white; }
    </style>
</head>
<body>
    <h1>Godot Coverage Report</h1>
    {% for file_path, data in coverage_data.items() %}
    <div class="file-section">
        <div class="file-header">
            {{ file_path }}
            {% if data.percentage >= 80 %}
            <span class="badge badge-success">{{ data.percentage }}%</span>
            {% elif data.percentage >= 50 %}
            <span class="badge badge-warning">{{ data.percentage }}%</span>
            {% else %}
            <span class="badge badge-error">{{ data.percentage }}%</span>
            {% endif %}
            <span class="percentage">({{ data.covered_count }}/{{ data.total_count }} lines)</span>
        </div>
        {% for line_num in range(1, data.total_count + 1) if line_num in data.executable_lines %}
        {% if line_num in data.executed_lines %}
        <div class="line covered">{{ line_num }}: covered</div>
        {% else %}
        <div class="line uncovered">{{ line_num }}: NOT covered</div>
        {% endif %}
        {% endfor %}
    </div>
    {% endfor %}
</body>
</html>
''')

    html = template.render(coverage_data=coverage_data)
    Path(output_path).write_text(html)



def main():
    """Main entry point for the script."""
    parser = argparse.ArgumentParser(description='Parse Godot coverage data and generate reports')
    parser.add_argument('--input', help='Path to coverage.json file')
    parser.add_argument('--output', help='Output path for HTML report')
    parser.add_argument('--json-output', action='store_true', help='Output overall coverage as JSON for CI/CD')

    args = parser.parse_args()

    if not args.input:
        print("Error: --input argument is required")
        print("Usage: python3 scripts/parse_godot_coverage.py --input=coverage.json --output=report.html")
        sys.exit(1)

    # Parse coverage data
    coverage_data = parse_coverage_json(args.input)

    # If json-output specified, output JSON and exit
    if args.json_output:
        overall = calculate_overall_coverage(coverage_data)
        result = {
            "overall_percentage": overall,
            "per_file": get_per_file_coverage(coverage_data)
        }
        print(json.dumps(result))
        sys.exit(0)

    # If output specified, generate HTML report
    if args.output:
        # Ensure output directory exists
        Path(args.output).parent.mkdir(parents=True, exist_ok=True)
        generate_html_report(coverage_data, args.output)
        print(f"Generated HTML coverage report: {args.output}")

    # Calculate and print overall coverage
    overall = calculate_overall_coverage(coverage_data)
    print(f"Overall Godot line coverage: {overall}%")

    # Print per-file coverage
    print("\nPer-file coverage:")
    for file_path, data in sorted(coverage_data.items()):
        if isinstance(data, dict):
            percentage = data.get('percentage', 0.0)
            covered = data.get('covered_count', 0)
            total = data.get('total_count', 0)
            print(f"  {file_path}: {percentage}% ({covered}/{total} lines)")


if __name__ == '__main__':
    main()
